import { Organization, UserProfile } from "@/types/auth";
import { Candidate, ScoringCriterion, CandidateNote, CandidateCriterionScore } from "@/types/candidate";
import { EmailTemplate, EmailLog } from "@/types/email";
import { OfferLetterTemplate, OfferLetter } from "@/types/offer";
import { IntegrationConfig, AuditLog } from "@/types/database";

export const MOCK_ORGANIZATION: Organization = {
  id: "org_default",
  name: "HireFlow Technologies Inc.",
  logo_url: "https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=120&h=120&fit=crop&crop=faces",
  email: "talent@hireflow.io",
  phone: "+1 (415) 890-2100",
  address: "100 Innovation Way, Suite 400, San Francisco, CA 94105",
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-01-01T00:00:00Z",
};

export const MOCK_USERS: UserProfile[] = [
  {
    id: "usr_admin_01",
    user_id: "usr_admin_01",
    organization_id: "org_default",
    full_name: "Sarah Jenkins",
    email: "admin@hireflow.io",
    avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop",
    role: "super_admin",
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "usr_recruiter_01",
    user_id: "usr_recruiter_01",
    organization_id: "org_default",
    full_name: "Alex Morgan",
    email: "recruiter@hireflow.io",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop",
    role: "recruiter",
    created_at: "2026-01-12T11:00:00Z",
    updated_at: "2026-01-12T11:00:00Z",
  },
  {
    id: "usr_reviewer_01",
    user_id: "usr_reviewer_01",
    organization_id: "org_default",
    full_name: "Dr. Marcus Vance",
    email: "reviewer@hireflow.io",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop",
    role: "reviewer",
    created_at: "2026-01-15T09:30:00Z",
    updated_at: "2026-01-15T09:30:00Z",
  },
  {
    id: "usr_viewer_01",
    user_id: "usr_viewer_01",
    organization_id: "org_default",
    full_name: "Elena Rostova",
    email: "viewer@hireflow.io",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop",
    role: "viewer",
    created_at: "2026-01-18T14:00:00Z",
    updated_at: "2026-01-18T14:00:00Z",
  },
];

export const MOCK_SCORING_CRITERIA: ScoringCriterion[] = [
  {
    id: "crit_01",
    organization_id: "org_default",
    name: "Education & Academic Credentials",
    description: "Evaluates relevant degrees (B.S., M.S., Ph.D.) and academic rigor.",
    weight: 20,
    maximum_score: 100,
    minimum_requirement: "Bachelor's degree in CS, Engineering, or relevant field",
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "crit_02",
    organization_id: "org_default",
    name: "Years of Relevant Experience",
    description: "Direct hands-on experience and track record in similar production roles.",
    weight: 25,
    maximum_score: 100,
    minimum_requirement: "3+ years for mid-level, 5+ for senior roles",
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "crit_03",
    organization_id: "org_default",
    name: "Technical & Core Skills Match",
    description: "Alignment with required technology stack, frameworks, and architecture.",
    weight: 25,
    maximum_score: 100,
    minimum_requirement: "Proficiency in required tech stack",
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "crit_04",
    organization_id: "org_default",
    name: "Interview & Problem Solving",
    description: "Technical screen assessment, system design, and communication quality.",
    weight: 20,
    maximum_score: 100,
    minimum_requirement: "Passing score on technical take-home or live session",
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "crit_05",
    organization_id: "org_default",
    name: "Availability & Location Alignment",
    description: "Notice period, time zone overlap, and salary alignment with budget.",
    weight: 10,
    maximum_score: 100,
    minimum_requirement: "Available within 30-45 days",
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
];

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: "cand_01",
    organization_id: "org_default",
    full_name: "Eleanor Wright",
    email: "eleanor.wright@example.com",
    phone: "+1 (415) 555-0142",
    address: "742 Evergreen Terrace, San Francisco, CA 94107",
    date_of_birth: "1994-06-14",
    position: "Senior Full Stack Engineer",
    department: "Engineering",
    education: "M.S. Computer Science, Stanford University",
    experience: 6,
    skills: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "Tailwind CSS", "AWS"],
    certifications: ["AWS Certified Solutions Architect", "CKA Kubernetes"],
    resume_url: "https://example.com/resumes/eleanor_wright.pdf",
    portfolio_url: "https://eleanorwright.dev",
    linkedin_url: "https://linkedin.com/in/eleanor-wright-dev",
    application_date: "2026-09-18",
    score: 92,
    recommendation: "Strongly Recommended",
    status: "Offer Sent",
    source: "Google Form",
    assigned_reviewer_id: "usr_reviewer_01",
    assigned_reviewer_name: "Dr. Marcus Vance",
    salary_expectation: "$150,000 / year",
    availability: "Immediate",
    created_at: "2026-09-18T08:30:00Z",
    updated_at: "2026-09-23T14:10:00Z",
  },
  {
    id: "cand_02",
    organization_id: "org_default",
    full_name: "Aarav Sharma",
    email: "aarav.sharma@example.com",
    phone: "+1 (408) 555-0198",
    address: "320 Market St, San Jose, CA 95113",
    date_of_birth: "1992-11-03",
    position: "Staff Backend Architect",
    department: "Engineering",
    education: "B.Tech Computer Science, IIT Bombay",
    experience: 9,
    skills: ["Go", "Distributed Systems", "Kubernetes", "PostgreSQL", "Kafka", "gRPC", "Redis"],
    certifications: ["GCP Professional Cloud Architect"],
    resume_url: "https://example.com/resumes/aarav_sharma.pdf",
    portfolio_url: "https://github.com/aaravsharma",
    linkedin_url: "https://linkedin.com/in/aarav-sharma-tech",
    application_date: "2026-09-19",
    score: 96,
    recommendation: "Strongly Recommended",
    status: "Offer Accepted",
    source: "Google Form",
    assigned_reviewer_id: "usr_reviewer_01",
    assigned_reviewer_name: "Dr. Marcus Vance",
    salary_expectation: "$180,000 / year",
    availability: "15 Days",
    created_at: "2026-09-19T09:15:00Z",
    updated_at: "2026-09-24T16:00:00Z",
  },
  {
    id: "cand_03",
    organization_id: "org_default",
    full_name: "Maya Lin",
    email: "maya.lin@example.com",
    phone: "+1 (510) 555-0245",
    address: "1840 Shattuck Ave, Berkeley, CA 94709",
    date_of_birth: "1996-03-21",
    position: "Lead Product Designer",
    department: "Design",
    education: "B.Des Interaction Design, RISD",
    experience: 5,
    skills: ["Figma", "Design Systems", "User Research", "Prototyping", "HTML/CSS", "Wireframing"],
    certifications: ["NN/g UX Master Certified"],
    resume_url: "https://example.com/resumes/maya_lin.pdf",
    portfolio_url: "https://mayalin.design",
    linkedin_url: "https://linkedin.com/in/maya-lin-ux",
    application_date: "2026-09-20",
    score: 88,
    recommendation: "Strongly Recommended",
    status: "Selected",
    source: "Google Form",
    assigned_reviewer_id: "usr_recruiter_01",
    assigned_reviewer_name: "Alex Morgan",
    salary_expectation: "$135,000 / year",
    availability: "30 Days",
    created_at: "2026-09-20T11:00:00Z",
    updated_at: "2026-09-23T16:45:00Z",
  },
  {
    id: "cand_04",
    organization_id: "org_default",
    full_name: "Daniel Alvarez",
    email: "daniel.alvarez@example.com",
    phone: "+1 (206) 555-0371",
    address: "500 Pike St, Seattle, WA 98101",
    date_of_birth: "1995-08-19",
    position: "Senior Product Manager",
    department: "Product",
    education: "MBA, Wharton & B.S. Industrial Eng, Purdue",
    experience: 6,
    skills: ["Product Strategy", "Agile Scrum", "Data Analytics", "Jira", "SQL", "A/B Testing"],
    certifications: ["Pragmatic Institute Certified", "CSPO"],
    resume_url: "https://example.com/resumes/daniel_alvarez.pdf",
    portfolio_url: "https://danielalvarez.pm",
    linkedin_url: "https://linkedin.com/in/daniel-alvarez-pm",
    application_date: "2026-09-21",
    score: 84,
    recommendation: "Strongly Recommended",
    status: "Interview",
    source: "Google Form",
    assigned_reviewer_id: "usr_recruiter_01",
    assigned_reviewer_name: "Alex Morgan",
    salary_expectation: "$160,000 / year",
    availability: "Immediate",
    created_at: "2026-09-21T10:20:00Z",
    updated_at: "2026-09-22T15:30:00Z",
  },
  {
    id: "cand_05",
    organization_id: "org_default",
    full_name: "Zoe Kravitz-Miller",
    email: "zoe.km@example.com",
    phone: "+1 (312) 555-0489",
    address: "200 N Michigan Ave, Chicago, IL 60601",
    date_of_birth: "1997-12-05",
    position: "DevOps & Cloud Engineer",
    department: "Engineering",
    education: "B.S. Information Systems, UIUC",
    experience: 4,
    skills: ["Terraform", "Docker", "Kubernetes", "AWS", "CI/CD GitHub Actions", "Prometheus"],
    certifications: ["HashiCorp Certified Terraform Associate"],
    resume_url: "https://example.com/resumes/zoe_miller.pdf",
    portfolio_url: "https://zoemiller.cloud",
    linkedin_url: "https://linkedin.com/in/zoe-miller-cloud",
    application_date: "2026-09-21",
    score: 78,
    recommendation: "Recommended",
    status: "Shortlisted",
    source: "Google Form",
    assigned_reviewer_id: "usr_reviewer_01",
    assigned_reviewer_name: "Dr. Marcus Vance",
    salary_expectation: "$130,000 / year",
    availability: "1 Month",
    created_at: "2026-09-21T14:15:00Z",
    updated_at: "2026-09-22T11:00:00Z",
  },
  {
    id: "cand_06",
    organization_id: "org_default",
    full_name: "Ethan Walker",
    email: "ethan.walker@example.com",
    phone: "+1 (617) 555-0523",
    address: "77 Massachusetts Ave, Cambridge, MA 02139",
    date_of_birth: "1998-02-14",
    position: "Frontend Developer",
    department: "Engineering",
    education: "B.S. Computer Science, Northeastern",
    experience: 3,
    skills: ["React", "JavaScript", "HTML/CSS", "Redux", "Tailwind CSS"],
    certifications: ["Meta Frontend Professional Certificate"],
    resume_url: "https://example.com/resumes/ethan_walker.pdf",
    portfolio_url: "https://ethanwalker.io",
    linkedin_url: "https://linkedin.com/in/ethan-walker-web",
    application_date: "2026-09-22",
    score: 72,
    recommendation: "Recommended",
    status: "Under Review",
    source: "Google Form",
    assigned_reviewer_id: "usr_recruiter_01",
    assigned_reviewer_name: "Alex Morgan",
    salary_expectation: "$105,000 / year",
    availability: "Immediate",
    created_at: "2026-09-22T09:00:00Z",
    updated_at: "2026-09-22T09:00:00Z",
  },
  {
    id: "cand_07",
    organization_id: "org_default",
    full_name: "Priya Sengupta",
    email: "priya.sengupta@example.com",
    phone: "+1 (512) 555-0634",
    address: "1100 Congress Ave, Austin, TX 78701",
    date_of_birth: "1993-09-12",
    position: "Senior Data Scientist (ML/AI)",
    department: "Data Science",
    education: "Ph.D. Applied Machine Learning, UT Austin",
    experience: 7,
    skills: ["Python", "PyTorch", "LLMs", "RAG", "Scikit-Learn", "SQL", "MLOps", "FastAPI"],
    certifications: ["TensorFlow Developer Certified"],
    resume_url: "https://example.com/resumes/priya_sengupta.pdf",
    portfolio_url: "https://priyasengupta.ai",
    linkedin_url: "https://linkedin.com/in/priya-sengupta-ml",
    application_date: "2026-09-22",
    score: 95,
    recommendation: "Strongly Recommended",
    status: "Shortlisted",
    source: "Google Form",
    assigned_reviewer_id: "usr_reviewer_01",
    assigned_reviewer_name: "Dr. Marcus Vance",
    salary_expectation: "$175,000 / year",
    availability: "Immediate",
    created_at: "2026-09-22T13:40:00Z",
    updated_at: "2026-09-23T10:15:00Z",
  },
  {
    id: "cand_08",
    organization_id: "org_default",
    full_name: "Carlos Mendez",
    email: "carlos.mendez@example.com",
    phone: "+1 (305) 555-0745",
    address: "800 Brickell Ave, Miami, FL 33131",
    date_of_birth: "1996-05-18",
    position: "Enterprise Account Executive",
    department: "Sales",
    education: "B.A. Marketing, University of Florida",
    experience: 4,
    skills: ["B2B SaaS Sales", "Salesforce", "Outreach.io", "Contract Negotiation", "Lead Generation"],
    certifications: ["MEDDPICC Certified"],
    resume_url: "https://example.com/resumes/carlos_mendez.pdf",
    portfolio_url: "",
    linkedin_url: "https://linkedin.com/in/carlos-mendez-sales",
    application_date: "2026-09-23",
    score: 74,
    recommendation: "Recommended",
    status: "Under Review",
    source: "Google Form",
    assigned_reviewer_id: "usr_recruiter_01",
    assigned_reviewer_name: "Alex Morgan",
    salary_expectation: "$110,000 + OTE",
    availability: "2 Weeks",
    created_at: "2026-09-23T08:20:00Z",
    updated_at: "2026-09-23T08:20:00Z",
  },
  {
    id: "cand_09",
    organization_id: "org_default",
    full_name: "Hannah Schmidt",
    email: "hannah.schmidt@example.com",
    phone: "+1 (212) 555-0856",
    address: "350 5th Ave, New York, NY 10118",
    date_of_birth: "1991-01-29",
    position: "Head of People & Culture",
    department: "Human Resources",
    education: "M.S. Human Resource Management, NYU",
    experience: 8,
    skills: ["HR Strategy", "Talent Acquisition", "BambooHR", "Compensation Planning", "DEI Programs"],
    certifications: ["SHRM-SCP", "SPHR"],
    resume_url: "https://example.com/resumes/hannah_schmidt.pdf",
    portfolio_url: "",
    linkedin_url: "https://linkedin.com/in/hannah-schmidt-hr",
    application_date: "2026-09-23",
    score: 91,
    recommendation: "Strongly Recommended",
    status: "Interview",
    source: "Google Form",
    assigned_reviewer_id: "usr_admin_01",
    assigned_reviewer_name: "Sarah Jenkins",
    salary_expectation: "$145,000 / year",
    availability: "30 Days",
    created_at: "2026-09-23T11:00:00Z",
    updated_at: "2026-09-24T09:30:00Z",
  },
  {
    id: "cand_10",
    organization_id: "org_default",
    full_name: "Kevin Patel",
    email: "kevin.patel@example.com",
    phone: "+1 (704) 555-0967",
    address: "100 N Tryon St, Charlotte, NC 28202",
    date_of_birth: "1999-07-11",
    position: "Junior QA Automation Engineer",
    department: "Engineering",
    education: "B.S. Software Engineering, UNC Charlotte",
    experience: 1,
    skills: ["Cypress", "Selenium", "JavaScript", "Jest", "Postman"],
    certifications: ["ISTQB Foundation Level"],
    resume_url: "https://example.com/resumes/kevin_patel.pdf",
    portfolio_url: "https://github.com/kevinpatelqa",
    linkedin_url: "https://linkedin.com/in/kevin-patel-qa",
    application_date: "2026-09-23",
    score: 58,
    recommendation: "Review Required",
    status: "On Hold",
    source: "Google Form",
    assigned_reviewer_id: "usr_reviewer_01",
    assigned_reviewer_name: "Dr. Marcus Vance",
    salary_expectation: "$75,000 / year",
    availability: "Immediate",
    created_at: "2026-09-23T15:10:00Z",
    updated_at: "2026-09-24T10:00:00Z",
  },
  {
    id: "cand_11",
    organization_id: "org_default",
    full_name: "Rochelle Dubois",
    email: "rochelle.dubois@example.com",
    phone: "+1 (619) 555-1078",
    address: "401 B St, San Diego, CA 92101",
    date_of_birth: "1994-04-09",
    position: "Senior Security Engineer",
    department: "Engineering",
    education: "M.S. Cybersecurity, Georgia Tech",
    experience: 6,
    skills: ["SOC 2 Compliance", "Penetration Testing", "AWS IAM", "OAuth2", "Vault", "SIEM"],
    certifications: ["CISSP", "OSCP"],
    resume_url: "https://example.com/resumes/rochelle_dubois.pdf",
    portfolio_url: "https://rochelledubois.sec",
    linkedin_url: "https://linkedin.com/in/rochelle-dubois-sec",
    application_date: "2026-09-24",
    score: 89,
    recommendation: "Strongly Recommended",
    status: "New",
    source: "Google Form",
    assigned_reviewer_id: "usr_reviewer_01",
    assigned_reviewer_name: "Dr. Marcus Vance",
    salary_expectation: "$165,000 / year",
    availability: "2 Weeks",
    created_at: "2026-09-24T06:45:00Z",
    updated_at: "2026-09-24T06:45:00Z",
  },
  {
    id: "cand_12",
    organization_id: "org_default",
    full_name: "Bradley Cooper-Smith",
    email: "bradley.cs@example.com",
    phone: "+1 (303) 555-1189",
    address: "1700 Lincoln St, Denver, CO 80203",
    date_of_birth: "1995-10-30",
    position: "Growth Marketing Manager",
    department: "Marketing",
    education: "B.A. Communications & Analytics, CU Boulder",
    experience: 5,
    skills: ["SEO/SEM", "Google Analytics 4", "HubSpot", "Paid Ads", "Conversion Rate Optimization"],
    certifications: ["Google Analytics Certified", "HubSpot Inbound"],
    resume_url: "https://example.com/resumes/bradley_cs.pdf",
    portfolio_url: "https://bradleygrowth.io",
    linkedin_url: "https://linkedin.com/in/bradley-cs-marketing",
    application_date: "2026-09-24",
    score: 81,
    recommendation: "Strongly Recommended",
    status: "New",
    source: "Google Form",
    assigned_reviewer_id: "usr_recruiter_01",
    assigned_reviewer_name: "Alex Morgan",
    salary_expectation: "$125,000 / year",
    availability: "Immediate",
    created_at: "2026-09-24T07:15:00Z",
    updated_at: "2026-09-24T07:15:00Z",
  },
  {
    id: "cand_13",
    organization_id: "org_default",
    full_name: "Jessica Taylor",
    email: "jessica.taylor@example.com",
    phone: "+1 (214) 555-1290",
    address: "2200 Ross Ave, Dallas, TX 75201",
    date_of_birth: "1997-05-14",
    position: "Financial Analyst",
    department: "Finance",
    education: "B.S. Finance & Accounting, SMU",
    experience: 3,
    skills: ["Financial Modeling", "Excel Advanced", "QuickBooks", "Budget Forecasting", "Tableau"],
    certifications: ["CFA Level 1 Passed"],
    resume_url: "https://example.com/resumes/jessica_taylor.pdf",
    portfolio_url: "",
    linkedin_url: "https://linkedin.com/in/jessica-taylor-fin",
    application_date: "2026-09-24",
    score: 68,
    recommendation: "Recommended",
    status: "New",
    source: "Google Form",
    assigned_reviewer_id: "usr_recruiter_01",
    assigned_reviewer_name: "Alex Morgan",
    salary_expectation: "$95,000 / year",
    availability: "Immediate",
    created_at: "2026-09-24T08:00:00Z",
    updated_at: "2026-09-24T08:00:00Z",
  },
  {
    id: "cand_14",
    organization_id: "org_default",
    full_name: "Timothy O'Connor",
    email: "timothy.oc@example.com",
    phone: "+1 (602) 555-1301",
    address: "201 E Washington St, Phoenix, AZ 85004",
    date_of_birth: "1990-12-19",
    position: "Senior Full Stack Engineer",
    department: "Engineering",
    education: "Self-taught & Coding Bootcamp",
    experience: 2,
    skills: ["HTML", "CSS", "Basic JavaScript", "jQuery"],
    certifications: [],
    resume_url: "https://example.com/resumes/timothy_oc.pdf",
    portfolio_url: "",
    linkedin_url: "https://linkedin.com/in/timothy-oc",
    application_date: "2026-09-24",
    score: 42,
    recommendation: "Not Recommended",
    status: "Rejected",
    source: "Google Form",
    assigned_reviewer_id: "usr_reviewer_01",
    assigned_reviewer_name: "Dr. Marcus Vance",
    salary_expectation: "$140,000 / year",
    availability: "Immediate",
    created_at: "2026-09-24T09:10:00Z",
    updated_at: "2026-09-24T12:30:00Z",
  },
  {
    id: "cand_15",
    organization_id: "org_default",
    full_name: "Ananya Gupta",
    email: "ananya.gupta@example.com",
    phone: "+1 (408) 555-1412",
    address: "450 Serra Mall, Stanford, CA 94305",
    date_of_birth: "1998-11-20",
    position: "Machine Learning Intern",
    department: "Data Science",
    education: "B.S. Artificial Intelligence (In Progress), Stanford",
    experience: 1,
    skills: ["Python", "TensorFlow", "Pandas", "Computer Vision", "Git"],
    certifications: ["DeepLearning.AI Specialization"],
    resume_url: "https://example.com/resumes/ananya_gupta.pdf",
    portfolio_url: "https://ananyagupta.me",
    linkedin_url: "https://linkedin.com/in/ananya-gupta-ai",
    application_date: "2026-09-24",
    score: 83,
    recommendation: "Strongly Recommended",
    status: "Shortlisted",
    source: "Google Form",
    assigned_reviewer_id: "usr_reviewer_01",
    assigned_reviewer_name: "Dr. Marcus Vance",
    salary_expectation: "$50 / hour",
    availability: "Immediate",
    created_at: "2026-09-24T10:05:00Z",
    updated_at: "2026-09-24T11:40:00Z",
  },
  {
    id: "cand_16",
    organization_id: "org_default",
    full_name: "Marcus Aurelius Thorne",
    email: "marcus.thorne@example.com",
    phone: "+1 (503) 555-1523",
    address: "1120 SW 5th Ave, Portland, OR 97204",
    date_of_birth: "1988-04-16",
    position: "VP of Engineering",
    department: "Engineering",
    education: "Ph.D. Distributed Systems, MIT",
    experience: 14,
    skills: ["Engineering Leadership", "Executive Management", "Architecture", "System Scaling", "Budgeting"],
    certifications: [],
    resume_url: "https://example.com/resumes/marcus_thorne.pdf",
    portfolio_url: "https://marcusthorne.tech",
    linkedin_url: "https://linkedin.com/in/marcus-thorne-exec",
    application_date: "2026-09-17",
    score: 98,
    recommendation: "Strongly Recommended",
    status: "Offer Sent",
    source: "Referral",
    assigned_reviewer_id: "usr_admin_01",
    assigned_reviewer_name: "Sarah Jenkins",
    salary_expectation: "$260,000 / year + Equity",
    availability: "30 Days",
    created_at: "2026-09-17T14:00:00Z",
    updated_at: "2026-09-24T15:00:00Z",
  },
  {
    id: "cand_17",
    organization_id: "org_default",
    full_name: "Fatima Al-Mansoor",
    email: "fatima.mansoor@example.com",
    phone: "+1 (404) 555-1634",
    address: "191 Peachtree St NE, Atlanta, GA 30303",
    date_of_birth: "1995-02-27",
    position: "Mobile App Engineer (iOS/Swift)",
    department: "Engineering",
    education: "B.S. Software Engineering, Georgia Tech",
    experience: 5,
    skills: ["Swift", "SwiftUI", "Combine", "CoreData", "iOS Architecture", "XCTest"],
    certifications: ["Apple Certified Developer"],
    resume_url: "https://example.com/resumes/fatima_mansoor.pdf",
    portfolio_url: "https://apps.apple.com/developer/fatima",
    linkedin_url: "https://linkedin.com/in/fatima-mansoor-ios",
    application_date: "2026-09-20",
    score: 87,
    recommendation: "Strongly Recommended",
    status: "Interview",
    source: "Google Form",
    assigned_reviewer_id: "usr_reviewer_01",
    assigned_reviewer_name: "Dr. Marcus Vance",
    salary_expectation: "$140,000 / year",
    availability: "15 Days",
    created_at: "2026-09-20T16:30:00Z",
    updated_at: "2026-09-23T11:20:00Z",
  },
  {
    id: "cand_18",
    organization_id: "org_default",
    full_name: "Gregory House",
    email: "gregory.house@example.com",
    phone: "+1 (609) 555-1745",
    address: "100 Mercer St, Princeton, NJ 08540",
    date_of_birth: "1985-09-11",
    position: "Senior Data Scientist (ML/AI)",
    department: "Data Science",
    education: "M.D. & M.S. Biostatistics, Johns Hopkins",
    experience: 10,
    skills: ["Diagnostic AI", "Statistical Modeling", "Python", "R", "Clinical NLP"],
    certifications: [],
    resume_url: "https://example.com/resumes/gregory_house.pdf",
    portfolio_url: "",
    linkedin_url: "https://linkedin.com/in/greg-house-diagnostics",
    application_date: "2026-09-19",
    score: 89,
    recommendation: "Strongly Recommended",
    status: "Offer Rejected",
    source: "LinkedIn",
    assigned_reviewer_id: "usr_reviewer_01",
    assigned_reviewer_name: "Dr. Marcus Vance",
    salary_expectation: "$190,000 / year",
    availability: "Immediate",
    created_at: "2026-09-19T10:00:00Z",
    updated_at: "2026-09-24T11:00:00Z",
  },
  {
    id: "cand_19",
    organization_id: "org_default",
    full_name: "Lily Zhang",
    email: "lily.zhang@example.com",
    phone: "+1 (650) 555-1856",
    address: "1 Hacker Way, Menlo Park, CA 94025",
    date_of_birth: "1997-03-08",
    position: "Product Designer (UI/UX)",
    department: "Design",
    education: "B.S. Cognitive Science & HCI, UC San Diego",
    experience: 4,
    skills: ["Figma", "User Journey Mapping", "Design Thinking", "Interaction Design"],
    certifications: [],
    resume_url: "https://example.com/resumes/lily_zhang.pdf",
    portfolio_url: "https://lilyzhang.design",
    linkedin_url: "https://linkedin.com/in/lily-zhang-ux",
    application_date: "2026-09-24",
    score: 79,
    recommendation: "Recommended",
    status: "Under Review",
    source: "Google Form",
    assigned_reviewer_id: "usr_recruiter_01",
    assigned_reviewer_name: "Alex Morgan",
    salary_expectation: "$120,000 / year",
    availability: "3 Weeks",
    created_at: "2026-09-24T12:00:00Z",
    updated_at: "2026-09-24T12:00:00Z",
  },
  {
    id: "cand_20",
    organization_id: "org_default",
    full_name: "Darnell Washington",
    email: "darnell.wash@example.com",
    phone: "+1 (202) 555-1967",
    address: "1600 Pennsylvania Ave, Washington, DC 20006",
    date_of_birth: "1993-08-04",
    position: "Operations & HR Specialist",
    department: "Human Resources",
    education: "B.A. Public Administration, Howard University",
    experience: 5,
    skills: ["Workday", "Onboarding", "Compliance", "Benefits Administration", "Payroll"],
    certifications: ["SHRM-CP"],
    resume_url: "https://example.com/resumes/darnell_wash.pdf",
    portfolio_url: "",
    linkedin_url: "https://linkedin.com/in/darnell-washington-hr",
    application_date: "2026-09-24",
    score: 82,
    recommendation: "Strongly Recommended",
    status: "New",
    source: "Google Form",
    assigned_reviewer_id: "usr_recruiter_01",
    assigned_reviewer_name: "Alex Morgan",
    salary_expectation: "$98,000 / year",
    availability: "Immediate",
    created_at: "2026-09-24T13:30:00Z",
    updated_at: "2026-09-24T13:30:00Z",
  },
];

export const MOCK_NOTES: CandidateNote[] = [
  {
    id: "note_01",
    candidate_id: "cand_01",
    user_id: "usr_reviewer_01",
    user_name: "Dr. Marcus Vance",
    user_role: "Reviewer",
    note: "Eleanor aced the technical challenge on Next.js hydration and state management. Strong system architect capabilities.",
    tags: ["Technical Screen", "Strong Pass"],
    mentions: ["Alex Morgan"],
    created_at: "2026-09-20T14:30:00Z",
    updated_at: "2026-09-20T14:30:00Z",
  },
  {
    id: "note_02",
    candidate_id: "cand_01",
    user_id: "usr_recruiter_01",
    user_name: "Alex Morgan",
    user_role: "Recruiter",
    note: "Discussed offer details. Candidate is very enthusiastic and confirmed start date for October 15th.",
    tags: ["Offer Negotiation"],
    mentions: ["Sarah Jenkins"],
    created_at: "2026-09-23T10:00:00Z",
    updated_at: "2026-09-23T10:00:00Z",
  },
  {
    id: "note_03",
    candidate_id: "cand_02",
    user_id: "usr_reviewer_01",
    user_name: "Dr. Marcus Vance",
    user_role: "Reviewer",
    note: "Outstanding performance in distributed system design (Kafka + Go). Unanimous hire recommendation.",
    tags: ["Executive Pass", "Senior"],
    mentions: [],
    created_at: "2026-09-22T16:00:00Z",
    updated_at: "2026-09-22T16:00:00Z",
  },
];

export const MOCK_EMAIL_TEMPLATES: EmailTemplate[] = [
  {
    id: "tpl_01",
    organization_id: "org_default",
    name: "Application Received Confirmation",
    template_type: "application_received",
    subject: "Thank you for applying for {{position}} at {{company_name}}",
    body: `Hi {{candidate_name}},

Thank you for your interest in {{company_name}}! We have successfully received your application for the {{position}} role in our {{department}} department on {{application_date}}.

Our talent team is actively reviewing your qualifications and portfolio. You can expect an update from us within 3-5 business days.

Best regards,
{{recruiter_name}}
Talent Acquisition Team | {{company_name}}`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "tpl_02",
    organization_id: "org_default",
    name: "Application Under Review Update",
    template_type: "application_under_review",
    subject: "Your application for {{position}} is currently under review",
    body: `Hi {{candidate_name}},

We wanted to give you a quick update regarding your application for {{position}} at {{company_name}}.

Our hiring managers are currently evaluating your profile. Your experience and skills are looking promising, and we are working diligently through our review stage.

We will reach out with the next steps shortly!

Warm regards,
{{recruiter_name}}
{{company_name}}`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "tpl_03",
    organization_id: "org_default",
    name: "Candidate Shortlisted Notification",
    template_type: "shortlisted",
    subject: "Exciting News: You have been shortlisted for {{position}} at {{company_name}}!",
    body: `Dear {{candidate_name}},

Congratulations! Based on our initial evaluation (Score: {{candidate_score}}), we are excited to inform you that you have been shortlisted for the {{position}} position at {{company_name}}.

We were particularly impressed with your background and achievements. Our team would love to move forward with the interview stage.

Our recruiting coordinator will be in touch with available interview slots.

Best regards,
{{recruiter_name}}
{{company_name}}`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "tpl_04",
    organization_id: "org_default",
    name: "Technical Interview Invitation",
    template_type: "interview_invitation",
    subject: "Interview Invitation: {{position}} at {{company_name}}",
    body: `Hi {{candidate_name}},

We would love to invite you for a 45-minute technical interview for the {{position}} position.

Proposed Date/Time: {{interview_date}}
Format: Google Meet / Virtual Video Session

During this conversation, we'll dive into your past engineering projects, review technical architecture, and give you plenty of time to ask questions about our culture and roadmap.

Please confirm if this time works for you or reply with 2-3 alternate times.

Looking forward to our conversation!

Best,
{{recruiter_name}}
{{company_name}}`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "tpl_05",
    organization_id: "org_default",
    name: "Selection Notification",
    template_type: "selection_notification",
    subject: "Congratulations! You have been selected for {{position}} at {{company_name}}",
    body: `Dear {{candidate_name}},

On behalf of the entire team at {{company_name}}, we are thrilled to inform you that you have been selected for the position of {{position}}!

The interview panel was deeply impressed by your technical depth, domain knowledge, and culture alignment. We believe you will be an invaluable asset to our {{department}} team.

We are preparing your official employment offer package and will send it across shortly for your review.

Congratulations once again!

Warm regards,
{{recruiter_name}}
{{company_name}}`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "tpl_06",
    organization_id: "org_default",
    name: "Rejection Notification",
    template_type: "rejection_notification",
    subject: "Update regarding your application for {{position}} at {{company_name}}",
    body: `Dear {{candidate_name}},

Thank you so much for taking the time to apply for the {{position}} position at {{company_name}} and for speaking with our team.

While your background and qualifications are commendable, after careful consideration, we have decided to proceed with other candidates whose experience more closely matches our immediate technical needs at this time.

We truly appreciate your interest in {{company_name}} and will keep your profile in our talent pool for future openings that match your skills.

We wish you the very best in your job search and future professional endeavors.

Sincerely,
{{recruiter_name}}
Talent Team | {{company_name}}`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "tpl_07",
    organization_id: "org_default",
    name: "Official Offer Letter Delivery",
    template_type: "offer_letter_email",
    subject: "Official Job Offer: {{position}} at {{company_name}}",
    body: `Dear {{candidate_name}},

We are thrilled to formally offer you the position of {{position}} at {{company_name}}!

Offer Highlights:
• Position: {{position}}
• Department: {{department}}
• Starting Compensation: {{salary}}
• Projected Joining Date: {{joining_date}}
• Offer Expiry Date: {{offer_expiry_date}}

You can review your detailed offer letter, download the official PDF, and submit your electronic acceptance directly through your candidate portal:
{{offer_letter_url}}

Please review and confirm your acceptance on or before {{offer_expiry_date}}.

We are all excited about the prospect of having you join our team and build the future together!

Warmest regards,
{{recruiter_name}}
{{company_name}}`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "tpl_08",
    organization_id: "org_default",
    name: "Offer Expiry Reminder",
    template_type: "offer_reminder",
    subject: "Reminder: Your offer for {{position}} at {{company_name}} expires soon",
    body: `Hi {{candidate_name}},

We wanted to send a friendly reminder regarding your job offer for the {{position}} position at {{company_name}}.

Your offer is currently scheduled to expire on {{offer_expiry_date}}. You can view and accept your offer at any time here:
{{offer_letter_url}}

If you have any questions about compensation, benefits, start dates, or anything else, please don't hesitate to reach out. We'd love to connect!

Best regards,
{{recruiter_name}}
{{company_name}}`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "tpl_09",
    organization_id: "org_default",
    name: "Offer Accepted - Welcome Aboard!",
    template_type: "offer_accepted_confirmation",
    subject: "Welcome to {{company_name}}, {{candidate_name}}! 🎉",
    body: `Dear {{candidate_name}},

We have received your signed acceptance of our offer for {{position}}! Welcome to the {{company_name}} family! 🎉

Our People Operations team is preparing your onboarding package, IT hardware provisioning, and first-week schedule. Your official start date is confirmed for {{joining_date}}.

We couldn't be more excited to work with you!

Warmest regards,
{{recruiter_name}} & The {{company_name}} Team`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "tpl_10",
    organization_id: "org_default",
    name: "Offer Rejected Confirmation",
    template_type: "offer_rejected_confirmation",
    subject: "Acknowledgement of Offer Response: {{position}}",
    body: `Dear {{candidate_name}},

Thank you for letting us know your decision regarding our offer for {{position}} at {{company_name}}.

While we are sorry that we won't be working together at this time, we respect your choice and appreciate your candid communication throughout our recruitment process.

We wish you tremendous success in your next chapter and hope our paths cross again in the future!

Best regards,
{{recruiter_name}}
{{company_name}}`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
];

export const MOCK_OFFER_TEMPLATES: OfferLetterTemplate[] = [
  {
    id: "off_tpl_01",
    organization_id: "org_default",
    name: "Standard Full-Time Employment Offer",
    content: `Dear {{candidate_name}},

We are pleased to extend an offer of employment with {{company_name}} as {{position}} in the {{department}} department.

Compensation & Benefits:
Your starting base salary will be {{salary}}, paid on a bi-weekly basis, subject to standard withholdings and taxes. You will also be eligible for comprehensive health insurance, dental, vision, 401(k) matching, and flexible paid time off.

Joining & Work Arrangement:
Your target start date will be {{joining_date}}. This position is designated as {{work_location}}, reporting to {{reporting_manager}}.

Terms & Conditions:
Employment with {{company_name}} is at-will. This offer is contingent on the successful completion of background checks and verification of professional credentials. This offer is valid through {{offer_expiry_date}}.`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "off_tpl_02",
    organization_id: "org_default",
    name: "Senior Leadership & Executive Offer",
    content: `Dear {{candidate_name}},

It is our great pleasure to offer you the senior leadership position of {{position}} at {{company_name}}.

Executive Compensation Package:
- Base Salary: {{salary}}
- Executive Performance Bonus: Target 25% of base compensation based on annual KPI milestones
- Equity Grant: Incentive Stock Options subject to board approval and standard 4-year vesting with a 1-year cliff
- Benefits: Executive health concierge, cell phone stipend, $5,000 annual executive development allowance

Start Date & Reporting:
Your target start date will be {{joining_date}}, reporting directly to {{reporting_manager}}.

Please confirm your acceptance by {{offer_expiry_date}}.`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "off_tpl_03",
    organization_id: "org_default",
    name: "Contractor & Internship Agreement",
    content: `Dear {{candidate_name}},

We are pleased to offer you a position as {{position}} at {{company_name}}.

Terms of Engagement:
- Compensation Rate: {{salary}}
- Term Duration: 3-6 months with potential conversion to full-time based on performance
- Expected Start Date: {{joining_date}}
- Location: {{work_location}}

Please sign and return this agreement prior to {{offer_expiry_date}}.`,
    enabled: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
];

export const MOCK_OFFER_LETTERS: OfferLetter[] = [
  {
    id: "off_letter_01",
    organization_id: "org_default",
    candidate_id: "cand_01",
    candidate_name: "Eleanor Wright",
    candidate_email: "eleanor.wright@example.com",
    template_id: "off_tpl_01",
    template_name: "Standard Full-Time Employment Offer",
    offer_number: "HF-OFF-2026-001",
    job_title: "Senior Full Stack Engineer",
    department: "Engineering",
    reporting_manager: "David Zhao (VP Engineering)",
    employment_type: "Full-time",
    work_location: "Hybrid (San Francisco HQ)",
    salary: "$150,000 / year",
    bonus_structure: "10% annual performance bonus",
    benefits: "Full medical/dental/vision coverage, 401(k) 4% match, $2,500 annual learning stipend, unlimited PTO",
    probation_period: "3 months",
    working_hours: "40 hrs/week, Mon-Fri",
    joining_date: "2026-10-15",
    expiry_date: "2026-10-01",
    signatory_name: "Sarah Jenkins",
    signatory_designation: "VP of People & Operations",
    status: "Sent",
    sent_at: "2026-09-23T14:10:00Z",
    created_at: "2026-09-23T14:00:00Z",
    updated_at: "2026-09-23T14:10:00Z",
  },
  {
    id: "off_letter_02",
    organization_id: "org_default",
    candidate_id: "cand_02",
    candidate_name: "Aarav Sharma",
    candidate_email: "aarav.sharma@example.com",
    template_id: "off_tpl_01",
    template_name: "Standard Full-Time Employment Offer",
    offer_number: "HF-OFF-2026-002",
    job_title: "Staff Backend Architect",
    department: "Engineering",
    reporting_manager: "David Zhao (VP Engineering)",
    employment_type: "Full-time",
    work_location: "Remote (US/Canada)",
    salary: "$180,000 / year",
    bonus_structure: "15% annual target bonus + 0.1% equity grant",
    benefits: "Comprehensive health package, $3,000 home office setup stipend, wellness allowance",
    probation_period: "3 months",
    working_hours: "Flexible 40 hrs/week",
    joining_date: "2026-10-10",
    expiry_date: "2026-09-30",
    signatory_name: "Sarah Jenkins",
    signatory_designation: "VP of People & Operations",
    status: "Accepted",
    sent_at: "2026-09-21T11:00:00Z",
    viewed_at: "2026-09-21T14:20:00Z",
    responded_at: "2026-09-24T16:00:00Z",
    response_comment: "Thrilled to accept! Looking forward to building the distributed architecture with the team.",
    candidate_signature_name: "Aarav Sharma",
    created_at: "2026-09-21T10:45:00Z",
    updated_at: "2026-09-24T16:00:00Z",
  },
  {
    id: "off_letter_03",
    organization_id: "org_default",
    candidate_id: "cand_16",
    candidate_name: "Marcus Aurelius Thorne",
    candidate_email: "marcus.thorne@example.com",
    template_id: "off_tpl_02",
    template_name: "Senior Leadership & Executive Offer",
    offer_number: "HF-OFF-2026-003",
    job_title: "VP of Engineering",
    department: "Engineering",
    reporting_manager: "Chief Executive Officer",
    employment_type: "Full-time Executive",
    work_location: "San Francisco HQ",
    salary: "$260,000 / year",
    bonus_structure: "25% target executive milestone bonus + 1.2% equity ISO",
    benefits: "Executive health plan, $10,000 relocation assistance, unlimited executive coaching",
    probation_period: "N/A",
    working_hours: "Executive Schedule",
    joining_date: "2026-11-01",
    expiry_date: "2026-10-05",
    signatory_name: "Sarah Jenkins",
    signatory_designation: "VP of People & Operations",
    status: "Sent",
    sent_at: "2026-09-24T15:00:00Z",
    created_at: "2026-09-24T14:30:00Z",
    updated_at: "2026-09-24T15:00:00Z",
  },
  {
    id: "off_letter_04",
    organization_id: "org_default",
    candidate_id: "cand_18",
    candidate_name: "Gregory House",
    candidate_email: "gregory.house@example.com",
    template_id: "off_tpl_01",
    template_name: "Standard Full-Time Employment Offer",
    offer_number: "HF-OFF-2026-004",
    job_title: "Senior Data Scientist (ML/AI)",
    department: "Data Science",
    reporting_manager: "Head of AI Research",
    employment_type: "Full-time",
    work_location: "Hybrid (New York)",
    salary: "$190,000 / year",
    benefits: "Full healthcare, 401(k), Conference travel budget",
    joining_date: "2026-10-01",
    expiry_date: "2026-09-28",
    signatory_name: "Sarah Jenkins",
    signatory_designation: "VP of People & Operations",
    status: "Rejected",
    sent_at: "2026-09-20T09:00:00Z",
    viewed_at: "2026-09-20T10:15:00Z",
    responded_at: "2026-09-24T11:00:00Z",
    response_comment: "Accepted competing offer closer to current clinic.",
    created_at: "2026-09-20T08:30:00Z",
    updated_at: "2026-09-24T11:00:00Z",
  },
];

export const MOCK_EMAIL_LOGS: EmailLog[] = [
  {
    id: "elog_01",
    organization_id: "org_default",
    candidate_id: "cand_01",
    candidate_name: "Eleanor Wright",
    template_id: "tpl_07",
    template_name: "Official Job Offer Delivery",
    recipient_email: "eleanor.wright@example.com",
    subject: "Official Job Offer: Senior Full Stack Engineer at HireFlow Technologies Inc.",
    body_preview: "We are thrilled to formally offer you the position of Senior Full Stack Engineer...",
    status: "Delivered",
    provider_message_id: "msg_resend_98a72b",
    sent_at: "2026-09-23T14:10:00Z",
    opened_at: "2026-09-23T14:25:00Z",
  },
  {
    id: "elog_02",
    organization_id: "org_default",
    candidate_id: "cand_02",
    candidate_name: "Aarav Sharma",
    template_id: "tpl_09",
    template_name: "Offer Accepted - Welcome Aboard!",
    recipient_email: "aarav.sharma@example.com",
    subject: "Welcome to HireFlow Technologies Inc., Aarav Sharma! 🎉",
    body_preview: "We have received your signed acceptance of our offer for Staff Backend Architect...",
    status: "Opened",
    provider_message_id: "msg_resend_77c19d",
    sent_at: "2026-09-24T16:05:00Z",
    opened_at: "2026-09-24T16:08:00Z",
  },
  {
    id: "elog_03",
    organization_id: "org_default",
    candidate_id: "cand_04",
    candidate_name: "Daniel Alvarez",
    template_id: "tpl_04",
    template_name: "Technical Interview Invitation",
    recipient_email: "daniel.alvarez@example.com",
    subject: "Interview Invitation: Senior Product Manager at HireFlow Technologies Inc.",
    body_preview: "We would love to invite you for a 45-minute technical interview...",
    status: "Clicked",
    provider_message_id: "msg_resend_44f81a",
    sent_at: "2026-09-22T15:30:00Z",
    opened_at: "2026-09-22T15:35:00Z",
    clicked_at: "2026-09-22T15:36:00Z",
  },
  {
    id: "elog_04",
    organization_id: "org_default",
    candidate_id: "cand_14",
    candidate_name: "Timothy O'Connor",
    template_id: "tpl_06",
    template_name: "Rejection Notification",
    recipient_email: "timothy.oc@example.com",
    subject: "Update regarding your application for Senior Full Stack Engineer at HireFlow Technologies Inc.",
    body_preview: "Thank you so much for taking the time to apply for the position...",
    status: "Delivered",
    provider_message_id: "msg_resend_12e90c",
    sent_at: "2026-09-24T12:35:00Z",
    opened_at: "2026-09-24T13:00:00Z",
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "aud_01",
    organization_id: "org_default",
    user_id: "usr_recruiter_01",
    user_name: "Alex Morgan",
    user_role: "Recruiter",
    action: "STATUS_CHANGED",
    entity_type: "candidate",
    entity_id: "cand_01",
    metadata: { previousStatus: "Selected", newStatus: "Offer Sent", offerNumber: "HF-OFF-2026-001" },
    created_at: "2026-09-23T14:10:00Z",
  },
  {
    id: "aud_02",
    organization_id: "org_default",
    user_id: "usr_admin_01",
    user_name: "Sarah Jenkins",
    user_role: "Super Admin",
    action: "OFFER_GENERATED",
    entity_type: "offer_letter",
    entity_id: "off_letter_01",
    metadata: { candidate: "Eleanor Wright", salary: "$150,000 / year", role: "Senior Full Stack Engineer" },
    created_at: "2026-09-23T14:00:00Z",
  },
  {
    id: "aud_03",
    organization_id: "org_default",
    user_id: "usr_reviewer_01",
    user_name: "Dr. Marcus Vance",
    user_role: "Reviewer",
    action: "CANDIDATE_SCORED",
    entity_type: "candidate",
    entity_id: "cand_02",
    metadata: { score: 96, recommendation: "Strongly Recommended" },
    created_at: "2026-09-22T16:00:00Z",
  },
  {
    id: "aud_04",
    organization_id: "org_default",
    user_id: "usr_admin_01",
    user_name: "Sarah Jenkins",
    user_role: "Super Admin",
    action: "INTEGRATION_SYNCED",
    entity_type: "integration",
    entity_id: "int_google_01",
    metadata: { provider: "google_sheets", recordsImported: 8, duplicatesPrevented: 2 },
    created_at: "2026-09-24T06:00:00Z",
  },
  {
    id: "aud_05",
    organization_id: "org_default",
    user_id: "system",
    user_name: "System",
    user_role: "System",
    action: "OFFER_ACCEPTED",
    entity_type: "offer_letter",
    entity_id: "off_letter_02",
    metadata: { candidate: "Aarav Sharma", offerNumber: "HF-OFF-2026-002" },
    created_at: "2026-09-24T16:00:00Z",
  },
];

export const MOCK_INTEGRATION: IntegrationConfig = {
  id: "int_google_01",
  organization_id: "org_default",
  provider: "google_sheets",
  spreadsheet_id: "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms",
  spreadsheet_url: "https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit#gid=0",
  worksheet_name: "Form Responses 1",
  auto_sync_enabled: true,
  sync_frequency: "15m",
  last_sync_at: "2026-09-24T18:30:00Z",
  sync_status: "success",
  total_synced_count: 24,
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-09-24T18:30:00Z",
};
